"""Constructor replicates the yices2 term_constructor_t enum."""
import yices_api as yapi


class Constructor:

    CONSTRUCTOR_ERROR = yapi.YICES_CONSTRUCTOR_ERROR
    BOOL_CONSTANT = yapi.YICES_BOOL_CONSTANT
    ARITH_CONSTANT = yapi.YICES_ARITH_CONSTANT
    BV_CONSTANT = yapi.YICES_BV_CONSTANT
    SCALAR_CONSTANT = yapi.YICES_SCALAR_CONSTANT
    VARIABLE = yapi.YICES_VARIABLE
    UNINTERPRETED_TERM = yapi.YICES_UNINTERPRETED_TERM
    ITE_TERM = yapi.YICES_ITE_TERM
    APP_TERM = yapi.YICES_APP_TERM
    UPDATE_TERM = yapi.YICES_UPDATE_TERM
    TUPLE_TERM = yapi.YICES_TUPLE_TERM
    EQ_TERM = yapi.YICES_EQ_TERM
    DISTINCT_TERM = yapi.YICES_DISTINCT_TERM
    FORALL_TERM = yapi.YICES_FORALL_TERM
    LAMBDA_TERM = yapi.YICES_LAMBDA_TERM
    NOT_TERM = yapi.YICES_NOT_TERM
    OR_TERM = yapi.YICES_OR_TERM
    XOR_TERM = yapi.YICES_XOR_TERM
    BV_ARRAY = yapi.YICES_BV_ARRAY
    BV_DIV = yapi.YICES_BV_DIV
    BV_REM = yapi.YICES_BV_REM
    BV_SDIV = yapi.YICES_BV_SDIV
    BV_SREM = yapi.YICES_BV_SREM
    BV_SMOD = yapi.YICES_BV_SMOD
    BV_SHL = yapi.YICES_BV_SHL
    BV_LSHR = yapi.YICES_BV_LSHR
    BV_ASHR = yapi.YICES_BV_ASHR
    BV_GE_ATOM = yapi.YICES_BV_GE_ATOM
    BV_SGE_ATOM = yapi.YICES_BV_SGE_ATOM
    ARITH_GE_ATOM = yapi.YICES_ARITH_GE_ATOM
    ARITH_ROOT_ATOM = yapi.YICES_ARITH_ROOT_ATOM
    ABS = yapi.YICES_ABS
    CEIL = yapi.YICES_CEIL
    FLOOR = yapi.YICES_FLOOR
    RDIV = yapi.YICES_RDIV
    IDIV = yapi.YICES_IDIV
    IMOD = yapi.YICES_IMOD
    IS_INT_ATOM = yapi.YICES_IS_INT_ATOM
    DIVIDES_ATOM = yapi.YICES_DIVIDES_ATOM
    SELECT_TERM = yapi.YICES_SELECT_TERM
    BIT_TERM = yapi.YICES_BIT_TERM
    BV_SUM = yapi.YICES_BV_SUM
    ARITH_SUM = yapi.YICES_ARITH_SUM
    POWER_PRODUCT = yapi.YICES_POWER_PRODUCT
